// Mocks generated by Mockito 5.4.6 from annotations
// in rivulet/test/integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:rivulet/api/real_debrid_client.dart' as _i4;
import 'package:rivulet/api/torrentio_client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TorrentioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTorrentioClient extends _i1.Mock implements _i2.TorrentioClient {
  MockTorrentioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.TorrentioStream>> getStreams(String? imdbId) =>
      (super.noSuchMethod(
            Invocation.method(#getStreams, [imdbId]),
            returnValue: _i3.Future<List<_i2.TorrentioStream>>.value(
              <_i2.TorrentioStream>[],
            ),
          )
          as _i3.Future<List<_i2.TorrentioStream>>);
}

/// A class which mocks [RealDebridClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealDebridClient extends _i1.Mock implements _i4.RealDebridClient {
  MockRealDebridClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setToken(String? token) => super.noSuchMethod(
    Invocation.method(#setToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<String> addMagnet(String? magnet) =>
      (super.noSuchMethod(
            Invocation.method(#addMagnet, [magnet]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#addMagnet, [magnet]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<Map<String, dynamic>> getTorrentInfo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTorrentInfo, [id]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> selectFiles(String? id, String? files) =>
      (super.noSuchMethod(
            Invocation.method(#selectFiles, [id, files]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> unrestrictLink(String? link) =>
      (super.noSuchMethod(
            Invocation.method(#unrestrictLink, [link]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
