import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

part 'app_database.g.dart';

// Tables

/// Stores metadata for offline browsing
class MediaCache extends Table {
  TextColumn get uuid => text()();
  TextColumn get metadataJson => text()(); // JSON blob
  DateTimeColumn get lastAccessed =>
      dateTime().withDefault(currentDateAndTime)();

  @override
  Set<Column> get primaryKey => {uuid};
}

/// Stores download tasks and their progress
class Downloads extends Table {
  TextColumn get taskId => text()(); // Generated by background_downloader
  TextColumn get mediaUuid => text().references(MediaCache, #uuid)();
  TextColumn get filePath => text().nullable()();
  TextColumn get status => textEnum<DownloadTaskStatus>()();
  RealColumn get progress => real().withDefault(const Constant(0.0))();

  // Specific metadata to make listing easier without parsing generic JSON
  TextColumn get title => text()();
  TextColumn get posterPath => text().nullable()();
  TextColumn get backdropPath => text().nullable()(); // New
  TextColumn get type => text()(); // 'movie' or 'episode'
  TextColumn get overview => text().nullable()(); // New: Show/Movie overview
  TextColumn get imdbId => text().nullable()(); // New
  RealColumn get voteAverage => real().nullable()(); // New

  // For episodes
  TextColumn get showTitle => text().nullable()();
  IntColumn get seasonNumber => integer().nullable()();
  IntColumn get episodeNumber => integer().nullable()();
  TextColumn get episodeOverview => text().nullable()(); // New
  TextColumn get episodeStillPath => text().nullable()(); // New
  TextColumn get episodeTitle => text().nullable()(); // New v3

  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  @override
  Set<Column> get primaryKey => {taskId};
}

// Enums matched to background_downloader or simplified
enum DownloadTaskStatus {
  enqueued,
  running,
  completed,
  failed,
  canceled,
  paused,
  notFound, // if record exists but file gone
}

@DriftDatabase(tables: [MediaCache, Downloads])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      onUpgrade: (Migrator m, int from, int to) async {
        if (from < 2) {
          // Schema v2 changes:
          // Added columns to Downloads table:
          // overview, backdropPath, imdbId, voteAverage
          // episodeOverview, episodeStillPath
          await m.addColumn(downloads, downloads.overview);
          await m.addColumn(downloads, downloads.backdropPath);
          await m.addColumn(downloads, downloads.imdbId);
          await m.addColumn(downloads, downloads.voteAverage);
          await m.addColumn(downloads, downloads.episodeOverview);
          await m.addColumn(downloads, downloads.episodeStillPath);
        }
        if (from < 3) {
          // Schema v3: Episode Title
          await m.addColumn(downloads, downloads.episodeTitle);
        }
      },
    );
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'rivulet_db.sqlite'));
    return NativeDatabase(file);
  });
}

// Riverpod Provider
@Riverpod(keepAlive: true)
AppDatabase appDatabase(Ref ref) {
  return AppDatabase();
}
